### ISSUE TITLE
Move PyBaMM requirements to release version

### ISSUE THREAD

**Issue by ejfdickinson** [dandeliion-team/dandeliion-client-api-feedback#6]
@jschewts Since PyBaMM 24.5 was released recently, could you please update the PyBaMM requirements for `dandeliion-client` to the following, and break all dependency on / support for the PyBaMM release candidates? Or is there any reason that this is not possible?

```
pybamm >= 24.5
```

**Comment by jschewts** [comment]
Sorry, I just missed that release. I have now made an official release for v0.2.0 on pypi with an updated dependency on the pybamm 24.5 release.

**Comment by ejfdickinson** [comment]
@jschewts Thanks for that!

I am getting a hang waiting for `solve()` to return, after the simulation has finished on the server (results are present through the web UI). This doesn't happen with `v0.2.0rc3`.

Any ideas?

**Comment by ejfdickinson** [comment]
It seems to be working again now (..?!).

Disregard for the moment - I'll let you know if we uncover any repeatable issues.

**Comment by jschewts** [comment]
It uses websockets in the background for status signals between the client and server. If the connection breaks (e.g. due to networking issues) and not re-established until the server signals back about the completion that could happen. It wasn't an issue at all during all my test runs (after I fixed a protocol issue some time ago), but if that occurs now in your runs, we probably should see if I can adapt the client code to have some timeout to check the status more 'pro-actively'.

**Comment by ejfdickinson** [comment]
Thanks for the comment and suggestion @jschewts. I am happy that we can investigate this by larger-scale testing and that you can close this issue now.
